function [fitresult, gof] = createFit(bVals, testsignal)

    %CREATEFIT(BVALS,TESTSIGNAL)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input : bVals
    %      Y Output: testsignal
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 21-Jul-2022 10:16:15
    
    
    %% Fit: 'untitled fit 1'.
    [xData, yData] = prepareCurveData( bVals, testsignal );
    
    % Set up fittype and options.
    ft = fittype( 'exp1' );
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    opts.Display = 'Off';
    opts.StartPoint = [0.967066852882677 -0.00205833566758353];
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );

end


